version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    # network_mode: host
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh /app/start.sh 