services:
  api:
    build:
      context: ./backend
      target: dev
    networks:
      - main
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
    command: sh /app/start.sh

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    networks:
      - main
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  sqlc:
    build:
      context: ./backend
      dockerfile: Dockerfile.sqlc
    volumes:
      - ./backend:/app
    working_dir: /app
    entrypoint: ["sleep", "infinity"]

  migrations:
    image: amacneil/dbmate:latest
    depends_on:
      - db
    networks:
      - main
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    volumes:
      - ./backend/internal/database/migrations:/db/migrations
    command: [ "up" ]

volumes:
  pgdata:

networks:
  main:
    name: main
