services:
  api:
    build:
      context: ./backend
      target: dev
    networks:
      - main
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env
#    environment:
#      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
    command: sh /app/start.sh

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    networks:
      - main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  sqlc:
    build:
      context: ./backend
      dockerfile: Dockerfile.sqlc
    volumes:
      - ./backend:/app
    working_dir: /app
    entrypoint: ["sleep", "infinity"]

volumes:
  pgdata:

networks:
  main:
    name: main
