services:
  api:
    build:
      context: ./backend
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: sh /app/start.sh

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: sh /app/start.sh 

volumes:
  pgdata:
