services:
  api:
    build:
      context: ./api
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    working_dir: /app

  front:
    image: openresty/openresty:latest
    volumes:
      - ./app/public:/var/www
      - ./docker/app/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
