services:
  api:
    image: nginx:latest
    volumes:
      - ./api/public:/var/www
      - ./docker/app/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  front:
    image: openresty/openresty:latest
    volumes:
      - ./app/public:/var/www
      - ./docker/app/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
