services:
  api:
    build:
      context: ./backend
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: sh /app/start.sh 

volumes:
  pgdata:
