FROM golang:1.21-alpine

RUN apk add --no-cache curl unzip

RUN curl -sSL https://github.com/sqlc-dev/sqlc/releases/download/v1.25.0/sqlc_1.25.0_linux_amd64.tar.gz \
    | tar -xz -C /usr/local/bin

WORKDIR /app

ENTRYPOINT ["sleep", "infinity"]